title: Github pages with jekyll
author: 李晓
email: xiao.liunit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning Lab for github pages.

# social links
twitter_username: your-twitter-handle
github_username:  originalix

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
